"""Repository for prompt operations."""

from typing import NamedTuple

from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.tables import Prompt


class PromptWithConfig(NamedTuple):
    """Prompt with model and temperature config."""

    prompt: str
    model: str
    temperature: float


class PromptRepository:
    """Data access layer for prompts table."""

    def __init__(self, db: AsyncSession) -> None:
        """Initialize repository with database session."""
        self.db = db

    async def get_prompt(
        self,
        company_id: int,
        name: str,
        reason: str,
    ) -> str | None:
        """
        Fetch prompt content by company, name and reason.

        Args:
            company_id: Company ID for multi-tenancy
            name: Prompt name (e.g., "filter_obj_faq", "rag_summary")
            reason: Prompt reason/category

        Returns:
            Prompt content string or None if not found
        """
        result = await self.db.execute(
            select(Prompt.prompt).where(
                Prompt.company_id == company_id,
                Prompt.name == name,
                Prompt.reason == reason,
            )
        )
        return result.scalar_one_or_none()

    async def get_prompt_with_config(
        self,
        company_id: int,
        name: str,
        reason: str,
    ) -> PromptWithConfig | None:
        """
        Fetch prompt with model and temperature config.

        Args:
            company_id: Company ID for multi-tenancy
            name: Prompt name
            reason: Prompt reason/category

        Returns:
            PromptWithConfig with prompt, model, temperature or None
        """
        result = await self.db.execute(
            select(
                Prompt.prompt,
                Prompt.model,
                Prompt.temperature,
            ).where(
                Prompt.company_id == company_id,
                Prompt.name == name,
                Prompt.reason == reason,
            )
        )
        row = result.one_or_none()
        if not row:
            return None

        return PromptWithConfig(
            prompt=row.prompt or "",
            model=row.model or "gpt-4o-mini",
            temperature=row.temperature if row.temperature is not None else 0.3,
        )

    async def get_prompt_by_id(self, prompt_id: int) -> PromptWithConfig | None:
        """
        Fetch prompt by ID with model and temperature config.

        Args:
            prompt_id: The prompt ID

        Returns:
            PromptWithConfig with prompt, model, temperature or None
        """
        result = await self.db.execute(
            select(
                Prompt.prompt,
                Prompt.model,
                Prompt.temperature,
            ).where(Prompt.id == prompt_id)
        )
        row = result.one_or_none()
        if not row:
            return None

        return PromptWithConfig(
            prompt=row.prompt or "",
            model=row.model or "gpt-4o-mini",
            temperature=row.temperature if row.temperature is not None else 0.3,
        )

    async def insert_variable_prompt(
        self,
        company_id: int,
        name: str,
        prompt: str,
        reason: str,
        model: str,
        temperature: float,
    ) -> int:
        """
        Insert a variable prompt generated by AI.

        Args:
            company_id: Company ID for multi-tenancy
            name: Prompt name from AI response
            prompt: Prompt content from AI response
            reason: Prompt reason from AI response
            model: Model name for the prompt
            temperature: Temperature setting for the prompt

        Returns:
            ID of the inserted prompt
        """
        new_prompt = Prompt(
            company_id=company_id,
            name=name,
            prompt=prompt,
            reason=reason,
            model=model,
            temperature=temperature,
            type="variable",
            status=True,
        )
        self.db.add(new_prompt)
        await self.db.commit()
        await self.db.refresh(new_prompt)
        return new_prompt.id

    async def deactivate_prompt(self, prompt_id: int) -> None:
        """
        Marcar prompt como status=false.

        Args:
            prompt_id: ID of the prompt to deactivate
        """
        await self.db.execute(
            update(Prompt)
            .where(Prompt.id == prompt_id)
            .values(status=False)
        )
        await self.db.commit()
